zhuochun/md-writer

README.md

Update link to example config file, instead of changelog diff of that file.
Fix #40

docs(README.md): Update link to example config

---

lib/insert-link-view.coffee
spec/insert-link-view-spec.coffee

revise insert-link-view

---

lib/commands/publish-draft.coffee
lib/config-basic.coffee
lib/config.coffee
lib/utils.coffee
lib/views/insert-image-view.coffee
lib/views/new-file-view.coffee
spec/utils-spec.coffee
spec/views/new-file-view-spec.coffee

Hey, this is still a bit of a work in progress. I wanted to start the pull request to start a dialog on supporting getting paths from the project (Issue #43). If you have an idea on the TODOs below, or want to go with a different direction to getting the current path, feel free to let me know!
Current TODOs:
- The useCurrentProject is always true. Need to figure out what I'm doing wrong.
- I am assuming that the first path is the website path. I should probably figure out a way to guess the right path.

Added initial support for getting paths from project.

---

lib/commands/edit-line.coffee
spec/commands/edit-line-spec.coffee

Which cause conflicts with other packages

Fix editLine not aborting event

---

lib/utils.coffee
spec/utils-spec.coffee

Escape user input in untemplate

---

lib/commands/create-project-configs.coffee
lib/config.coffee
lib/config.cson
spec/config-spec.coffee

Remove the `new Configuration()`

Refactoring config.coffee

---

lib/utils.coffee
lib/views/insert-image-view.coffee
spec/utils-spec.coffee
spec/views/insert-image-view-spec.coffee

Fix image path to forward slash

---

CHANGELOG.md
lib/commands/publish-draft.coffee
lib/helpers/template-helper.coffee
lib/utils.coffee
lib/views/insert-image-view.coffee
lib/views/new-file-view.coffee
spec/utils-spec.coffee

Fix homedir not recognized

---

CHANGELOG.md
lib/config.coffee
lib/config.cson
lib/markdown-writer.coffee
spec/config-spec.coffee
spec/fixtures/dummy.cson

- Fix loading empty config file raise exception
- Log config file loading info in dev mode

Improve config file loading

---

CHANGELOG.md
lib/commands/open-cheat-sheet.coffee
spec/commands/open-cheat-sheet-spec.coffee

Fix open cheatsheet in Windows

---

lib/commands/format-text.coffee
lib/config.cson
lib/helpers/line-meta.coffee
lib/utils.coffee
spec/commands/edit-line-spec.coffee
spec/commands/format-text-spec.coffee
spec/helpers/line-meta-spec.coffee
spec/utils-spec.coffee

Support alpha order list

---

lib/utils.coffee
spec/utils-spec.coffee

Fix parsing complex link

---

lib/config-basic.coffee
lib/config.cson
lib/views/insert-image-view.coffee
spec/views/insert-image-view-spec.coffee

Rename image filename on copy

---

lib/views/insert-image-view.coffee

- Support overwrite image file when file path exists
- Fixes #162

Support overwrite image file

---

lib/utils.coffee
package.json

Fix #176
Bump package min required version

Fix atom deprecation 💾

---

lib/commands/open-link-in-browser.coffee
lib/markdown-writer.coffee
lib/utils.coffee
lib/views/insert-link-view.coffee
menus/menu.cson
package.json
spec/utils-spec.coffee

#151 Add new command to open link under cursor in browser

Open link under cursor in Browser

---

lib/commands/format-text.coffee
lib/helpers/line-meta.coffee
spec/commands/format-text-spec.coffee
spec/helpers/line-meta-spec.coffee

Fix invalid order list length exception

---

lib/commands/style-text.coffee

Keep text selection if text was selected at the start. Closes #182

Keep text selection on style-text

---

lib/views/insert-footnote-view.coffee
lib/views/insert-image-view.coffee
menus/menu.cson

- Group Footnote modifications in an atomic unit to allow one step undo/redo
- Add missing menu item

Minor fixes to Footnote

---

CHANGELOG.md
lib/commands/open-cheat-sheet.coffee
spec/commands/open-cheat-sheet-spec.coffee

Support markdown-preview-plus

---

CHANGELOG.md
keymaps/keymap.cson
lib/commands/edit-line.coffee
lib/markdown-writer.coffee
package.json
spec/commands/edit-line-spec.coffee

Improve undent list line, as mentioned in #223 
Bind to `shift-tab` by default.

Add `undent-list-line` command

---

CHANGELOG.md
lib/helpers/front-matter.coffee
spec/helpers/front-matter-spec.coffee

Fix https://github.com/zhuochun/md-writer/issues/136

Fix error parsing in FrontMatter

---

lib/commands/edit-line.coffee
spec/commands/edit-line-spec.coffee

Keep cursor position when indent/outdent

---

keymaps/sample-linux.cson
keymaps/sample-osx.cson
keymaps/sample-win32.cson
lib/commands/format-text.coffee
lib/commands/style-line.coffee
lib/config.cson
lib/markdown-writer.coffee
menus/menu.cson
package.json
spec/commands/style-line-spec.coffee

- Improve style-line logic to preserve cursor position before/after toggle
- Better support for Task list
- Add `format-order-list` replaces `correct-order-list-numbers`
- Add `toggle-mathblock-text` and `toggle-math-text`
- Update and reorganize menus

Improve style line and other changes

---

lib/commands/style-line.coffee
spec/commands/style-line-spec.coffee

Fix multiple lines style broke in change #255

Fix style multiple lines

---

lib/commands/edit-toc.coffee
lib/markdown-writer.coffee
package.json
spec/commands/edit-toc-spec.coffee

Provide an `update-toc` command for update hooks.

Provide an Update TOC command

---

lib/commands/publish-draft.coffee
lib/helpers/template-helper.coffee
lib/utils.coffee
lib/views/insert-image-clipboard-view.coffee
lib/views/insert-image-file-view.coffee
lib/views/new-file-view.coffee
spec/views/insert-image-file-view-spec.coffee

Fix siteProject lookup in case of multiple projects

---

lib/config.coffee
spec/config-spec.coffee

Support multiple projects when read project-specific configs.

Update project config read

---

lib/config.cson
lib/views/insert-link-view.coffee

Fold inline links at insert link

Fold inline links at insert link

---

lib/commands/publish-draft.coffee
lib/config.coffee
spec/helpers/front-matter-spec.coffee

Basic support for [Hugo](https://gohugo.io/documentation/) #206

Add Hugo Engine

---

lib/commands/edit-toc.coffee
spec/commands/edit-toc-spec.coffee

Fix Incomplete TOC handling

---

lib/commands/style-line.coffee
lib/config.cson
spec/commands/style-line-spec.coffee

Fix blockquote on indentations

---

lib/commands/edit-line.coffee
lib/helpers/line-meta.coffee
spec/commands/edit-line-spec.coffee
spec/helpers/line-meta-spec.coffee

Fix OL indent issue

---

CHANGELOG.md
LICENSE.md
lib/views/insert-image-file-view.coffee

Fixes #302
Found the documents from my own [answer](https://discuss.atom.io/t/how-to-create-a-file-dialog/11151/5) back from 6 years ago.

Update dialog usage

---

CHANGELOG.md
lib/commands/edit-line.coffee
lib/helpers/line-meta.coffee
spec/commands/edit-line-spec.coffee

Fix #299 
Update wiki https://github.com/zhuochun/md-writer/wiki/Settings#use-ordered-list-styles

Support olBullet
