zhuochun/md-writer

lib/publish-draft.coffee
fix #62 when the destination path does not exists. `fs.moveSync` will
try to create the destination path first.
=> Use `fs.moveSync` to publish draft

lib/publish-draft.coffee
Publish command was not working, throwing the require error. This simple import fix does the trick for me!
Atom 1.0.9
Linux Ubuntu 15.04
=> Fixed front-matter import in publish-draft command

CHANGELOG.md, keymaps/keymap.cson, keymaps/sample-linux.cson, keymaps/sample-osx.cson, keymaps/sample-win32.cson, lib/markdown-writer.coffee, spec/markdown-writer-spec.coffee
Skip markdown-writer command if autocomplete-plus is active. #98
=> Fix autocompleteplus conflicts

lib/commands/jump-to.coffee, lib/commands/publish-draft.coffee, lib/commands/style-line.coffee, lib/commands/style-text.coffee, lib/config.coffee, lib/helpers/front-matter.coffee, lib/helpers/template-helper.coffee, lib/utils.coffee, lib/views/insert-image-view.coffee, lib/views/manage-post-tags-view.coffee, lib/views/new-file-view.coffee, spec/commands/publish-draft-spec.coffee, spec/helpers/template-helper-spec.coffee, spec/utils-spec.coffee, spec/views/insert-image-view-spec.coffee, spec/views/new-file-view-spec.coffee
- Rename `regexpEscape` to `escapeRegExp`
- Improve `utils.dasherize` to `utils.slugize`
- Change all `{title}` to `{slug}`
- Added config `slugSeparator`
- Change all `<template>` to `{template}`
- Extract `template-helper`
- Added `utils.untemplate` to reverse a generated string based on template
- Use `templateHelper.create` for any template creation
- Added config `templateVariables` for custom variables
- Added config `frontMatterDate` for front matter date format
=> Refactoring work

lib/config.coffee
The [language-markdown](https://github.com/burodepeper/language-markdown) package promises to add support for more than just GFM. This includes the new CommonMark syntax, as well as front-matters, and a bunch of other goodies. As such, this package should apply to it, too.
=> Add support for language-markdown package

README.md, lib/config.coffee, lib/config.cson, lib/filetypes/asciidoc.cson, lib/helpers/line-meta.coffee, package.json, spec/config-spec.coffee
Add support of filetype specific configs.
This enables us to support other non-Markdown filetypes, but need similar writing/editing functionalities. E.g. Asciidoc/Mediawiki etc.
To support a new filetype:
- Add a config file, similar to `lib/filetypes/asciidoc.cson`
- Load this config file content in `lib/config.coffee`, e.g. `'source.asciidoc': CSON.readFileSync(configFile("filetypes", "asciidoc.cson"))`
There are many other areas to make the package more generic, e.g. regex in utils were designed to support Markdown only.
=> Add Filetype configs and Asciidoc filetype

coffeelint.json, lib/views/insert-image-view.coffee, lib/views/insert-link-view.coffee, lib/views/insert-table-view.coffee, lib/views/manage-front-matter-view.coffee, lib/views/new-file-view.coffee
Add CompositeDisposable to views, to dispose atom.commands events after view detached.
=> Add Disposable to views

lib/commands/jump-to.coffee, lib/config.cson, lib/markdown-writer.coffee, lib/utils.coffee, lib/views/insert-footnote-view.coffee, package.json, spec/commands/jump-to-spec.coffee, spec/utils-spec.coffee, spec/views/insert-footnote-view-spec.coffee
Support footnote:
- Insert footnote with single line content
- Update footnote label with selection or https://atom.io/packages/language-markdown (provides footnote highlights)
- Jump between footnotes
=> Support footnote

lib/config.coffee, spec/config-spec.coffee
The variable was accidentally removed when introduce filetypes support.
Fixes #168
=> Fix getSampleConfigFile

lib/utils.coffee
This fixes spec failure appeared on the latest Atom v1.14.3:
- Travis failure build: https://travis-ci.org/zhuochun/md-writer/builds/202995399
- appveyor failure build: https://ci.appveyor.com/project/zhuochun/md-writer/build/143
=> Fix buffer match.computedRange not available

README.md, lib/commands/insert-image.coffee, lib/markdown-writer.coffee, lib/views/insert-image-clipboard-view.coffee, lib/views/insert-image-file-view.coffee, package.json, spec/views/insert-image-file-view-spec.coffee
Related #159 
Commands:
- **markdown-writer:insert-image**: replaced the original command, and will choose to use `FileView` or `ClipboardView`
- **markdown-writer:insert-image-file**: the original insert image view
- **markdown-writer:insert-image-clipboard**: new insert image from clipboard view
=> Support insert image from clipboard

lib/views/insert-image-clipboard-view.coffee
Fix deprecated `toPng` in the latest Atom version (Electron)
=> Fix deprecated NativeImage toPng

lib/commands/fold-text.coffee, lib/markdown-writer.coffee, lib/utils.coffee, menus/menu.cson, package.json
New command `markdown-writer:fold-links` to fold inline links. Use default `editor:unfold-all` to unfold all.
E.g.
=> Add new command fold-links

lib/config.cson, lib/utils.coffee, lib/views/new-file-view.coffee, spec/utils-spec.coffee
Support #219. Usage:
1. Add new config `frontMatterCustomFields`
- key-value pair (fieldName: defaultValue), referenced by fieldName in template
2. Add the field to template
```
frontMatterCustomFields:
author: "Your Name Here"
frontMatter: """
---
layout: "{layout}"
title: "{title}"
author: "{author}"
date: "{date}"
---
"""
```
=> Add custom front matter fields

lib/commands/style-text.coffee, lib/config.cson, lib/utils.coffee
Add global default config `textRangeSelectBy: "nearestWord"` and individual text style `selectBy` config.
To addresses #143 , change to use `currentNonTrailWord`.
The accuracy still depends on word definition by Atom.
=> Support different text selection range config

CHANGELOG.md, lib/commands/style-line.coffee, spec/commands/style-line-spec.coffee
Fixes #257
- `::selectToEndOfLine()` -> Selects all the text from the current cursor position to the end of the **screen line**.
- `::selectToEndOfBufferLine()` -> Selects all the text from the current cursor position to the end of the **buffer line**.
=> Fix style line that spans multiple screen lines

CHANGELOG.md, lib/utils.coffee
Style Text (e.g. `codeblock`) will throw nil exception because `cursor.getCurrentParagraphBufferRange()` somehow returns undefined range on an empty line.
=> Fix undefined buffer range

CHANGELOG.md, README.md, lib/commands/edit-toc.coffee, lib/config.cson, lib/markdown-writer.coffee, menus/menu.cson, package-lock.json, package.json, spec/commands/edit-toc-spec.coffee
=> Add TOC support

README.md, lib/commands/edit-toc.coffee, spec/commands/edit-toc-spec.coffee
Add empty lines to TOC comment tags make them separated. To avoid some incompatibilities, e.g.
=> Add empty lines to TOC comment tags

lib/commands/edit-line.coffee, lib/helpers/line-meta.coffee, spec/helpers/line-meta-spec.coffee
Fixes #275
- Ignore Alpha List in indent/outdent
- Limit Alpha List to 2 chars.
=> Fix indent/outdent on Alpha List

lib/commands/style-line.coffee, lib/config.cson, spec/commands/style-line-spec.coffee
=> Improve UL/OL line implementation

CHANGELOG.md, lib/commands/edit-line.coffee, spec/commands/edit-line-spec.coffee
Changes:
- Handle different TabLength affects how list-indent should worked (#293)
- Refine on indentation check when TabLength == 4. Indentation for 2 spaces is 0.5 indentation
=> Handle different TabLength in edit-line commands
